//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_BillSales
    {
        public int ID_BillSale { get; set; }
        public int ID_Product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Total { get; set; }
        public double Price { get; set; }
    
        public virtual Bill_Sales Bill_Sales { get; set; }
        public virtual Product Product { get; set; }
    }
}
