//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion_Apply
    {
        public int ID_Event { get; set; }
        public int ID_BillSale { get; set; }
        public string Note { get; set; }
    
        public virtual Bill_Sales Bill_Sales { get; set; }
        public virtual Event Event { get; set; }
    }
}
